name: SQL_DBPublicGit
description: ''
version: 0.0.1
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/SQLJobDBAirlowPub:
    name: SQLJobDBAirlowPub
    description: ''
    fabricUID: 2729
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 25 1 *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-06-22 13:46:45'
    author: abhisheks+e2etests@prophecy.io
functions:
  author: null
  createdAt: '2023-06-22 13:42:28'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/testapprandommodel1:
    name: testapprandommodel1
    schema:
      providerType: Databricks
      fields:
      - name: c_tinyint
        dataType:
          type: TinyInt
      - name: c_smallint
        dataType:
          type: SmallInt
      - name: c_int
        dataType:
          type: Integer
      - name: c_bigint
        dataType:
          type: Bigint
      - name: c_float
        dataType:
          type: Float
      - name: c_double
        dataType:
          type: Float
      - name: c_string
        dataType:
          type: String
      - name: c_boolean
        dataType:
          type: Boolean
      - name: c_array
        dataType:
          type: Array
          dataType:
            type: String
      - name: c_struct
        dataType:
          type: Struct
          fields:
          - name: city
            dataType:
              type: String
          - name: state
            dataType:
              type: String
          - name: pin
            dataType:
              type: Bigint
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - models/testapprandommodel1.sql
    - .prophecy/ide/models/testapprandommodel1.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-06-22 13:42:51'
sqlMacros: {}
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/spark_catalog_qa_database:
    name: spark_catalog.qa_database
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2023-06-22 13:46:08'
    tables:
    - name: all_type_non_partitioned
      schema:
        providerType: databricks
        fields:
        - name: c_tinyint
          dataType:
            type: TinyInt
        - name: c_smallint
          dataType:
            type: SmallInt
        - name: c_int
          dataType:
            type: Integer
        - name: c_bigint
          dataType:
            type: Bigint
        - name: c_float
          dataType:
            type: Float
        - name: c_double
          dataType:
            type: Double
        - name: c_string
          dataType:
            type: String
        - name: c_boolean
          dataType:
            type: Boolean
        - name: c_array
          dataType:
            type: Array
            dataType:
              type: String
        - name: c_struct
          dataType:
            type: Struct
            fields:
            - name: city
              dataType:
                type: String
            - name: state
              dataType:
                type: String
            - name: pin
              dataType:
                type: Bigint
      description: null
      author: abhisheks+e2etests@prophecy.io
      createdAt: '2023-06-22 13:46:08'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: abhisheks+e2etests@prophecy.io
  createdAt: '2023-06-22 13:42:28'
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
